/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./ContactForm.module.css";

function ContactForm() {
  return (
    <form className={styles.contactForm}>
      <label htmlFor="name" className={styles.label}>
        Name :
      </label>
      <input type="text" id="name" className={styles.input} />

      <label htmlFor="email" className={styles.label}>
        Email :
      </label>
      <input type="email" id="email" className={styles.input} />

      <label htmlFor="message" className={styles.label}>
        Message :
      </label>
      <textarea id="message" className={styles.textarea}></textarea>

      <button type="submit" className={styles.submitButton}>
        Send Message
      </button>
    </form>
  );
}

export default ContactForm;
