/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./ContactInfo.module.css";

function ContactInfo() {
  const contactDetails = [
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/6c273000f56232c234f1fba1ff026c15815f43f45d434e3a1fdeddf09ce46642?placeholderIfAbsent=true&apiKey=27c8773822ca4ac8b9cf93169b3bed33",
      title: "Phone",
      content: "+94 775849312",
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/0d2e50ae8342f060630a95f802f69360bfa603d4885222ec753d219dd76d02db?placeholderIfAbsent=true&apiKey=27c8773822ca4ac8b9cf93169b3bed33",
      title: "Email",
      content: "othisiclothing@gmail.com",
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/7f5ff07be9ba789e8e985e5faa247453ec2910a1955658ce3684bc53736a080f?placeholderIfAbsent=true&apiKey=27c8773822ca4ac8b9cf93169b3bed33",
      title: "Address",
      content: "23/5,High level road,Nugegoda.",
    },
  ];

  return (
    <section className={styles.contactInfo}>
      {contactDetails.map((detail, index) => (
        <div key={index} className={styles.infoItem}>
          <img
            src={detail.icon}
            alt={detail.title}
            className={styles.infoIcon}
          />
          <div className={styles.infoContent}>
            <h3>{detail.title}</h3>
            <p>{detail.content}</p>
          </div>
        </div>
      ))}
    </section>
  );
}

export default ContactInfo;
