/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./ContactUs.module.css";
import Header from "./Header";
import ContactForm from "./ContactForm";
import ContactInfo from "./ContactInfo";
import Footer from "./Footer";

function ContactUs() {
  return (
    <div>
      <header >
        
        <div >
          <Header />
          
          <h1 className={styles.pageTitle}>Contact us</h1>
        </div>
      </header>
      <main className={styles.mainContent}>
        <div className={styles.contentWrapper}>
          <ContactForm />
          <ContactInfo />
        </div>
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/c7e2da88628b443878c7ae9a55c358a671b2ec25bc061c4e654fe4e0fae31809?placeholderIfAbsent=true&apiKey=27c8773822ca4ac8b9cf93169b3bed33"
          alt="Contact Map"
          className={styles.contactMap}
        />
      </main>
      <Footer />
    </div>
  );
}

export default ContactUs;
