/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./Footer.module.css";

function Footer() {
  const quickLinks = ["Home", "About", "Services", "Contact"];
  const socialIcons = [
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/a45fc6a40956ccccb8738bf4972082ee0c8506cabec091f36224e5a1f6fd22c3?placeholderIfAbsent=true&apiKey=27c8773822ca4ac8b9cf93169b3bed33",
      alt: "Facebook",
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/bfad15def37d2a473e9f31d175d45d923a2bc1eb9d0a70561b89d546f371bc72?placeholderIfAbsent=true&apiKey=27c8773822ca4ac8b9cf93169b3bed33",
      alt: "Twitter",
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/1058894cdc262021057390a64208e8478cf0fd6734ec96748b671cc2ac52f5b1?placeholderIfAbsent=true&apiKey=27c8773822ca4ac8b9cf93169b3bed33",
      alt: "Instagram",
    },
  ];

  return (
    <footer className={styles.footer}>
      <div className={styles.footerContent}>
        <section className={styles.aboutSection}>
          <h3>About Us</h3>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec
            odio. Praesent libero. Sed cursus ante dapibus diam.
          </p>
        </section>
        <section className={styles.linksSection}>
          <h3>Quick Links</h3>
          <ul>
            {quickLinks.map((link, index) => (
              <li key={index}>{link}</li>
            ))}
          </ul>
        </section>
        <section className={styles.socialSection}>
          <h3>Quick Links</h3>
          <div className={styles.socialIcons}>
            {socialIcons.map((icon, index) => (
              <img
                key={index}
                src={icon.src}
                alt={icon.alt}
                className={styles.socialIcon}
              />
            ))}
          </div>
        </section>
        <section className={styles.contactSection}>
          <h3>Contact US</h3>
          <p>
            Email: info@example.com
            <br />
            Phone: +123 456 7890
            <br />
            Address: 123 Street Name, City, Country
          </p>
        </section>
      </div>
      <div className={styles.copyright}>
        <hr className={styles.divider} />
        <p>2024 Your Website. All Rights Reserved.</p>
      </div>
    </footer>
  );
}

export default Footer;
