/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./CartItem.module.css";

const CartItem = ({ name, size, image, price }) => {
  return (
    <article className={styles.cartItem}>
      <div className={styles.productInfo}>
        <img src={image} alt={name} className={styles.productImage} />
        <div className={styles.productDetails}>
          <h3 className={styles.productName}>{name}</h3>
          <div className={styles.productSize}>
            <span>Size {size}</span>
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/dcb9b6f616a65f5c3f722bffbe49982ebe6117950239981a603afb73250ae272?placeholderIfAbsent=true&apiKey=27c8773822ca4ac8b9cf93169b3bed33"
              alt="Size indicator"
              className={styles.sizeIcon}
            />
          </div>
          <button className={styles.editButton}>
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/ff5ec5e6ecab6abc85ee0032b2bf100b4f5ab8ee08f011fdac04102cbf3331c0?placeholderIfAbsent=true&apiKey=27c8773822ca4ac8b9cf93169b3bed33"
              alt="Edit"
              className={styles.editIcon}
            />
            Edit order
          </button>
        </div>
      </div>
      <div className={styles.quantityControl}>
        <button
          className={styles.quantityButton}
          aria-label="Decrease quantity"
        >
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/eb28ab623f032923e5b2ede036e448b85cbcb5d2a8656a351d89970d25501e16?placeholderIfAbsent=true&apiKey=27c8773822ca4ac8b9cf93169b3bed33"
            alt=""
          />
        </button>
        <span className={styles.quantity}>Amount 1</span>
        <button
          className={styles.quantityButton}
          aria-label="Increase quantity"
        >
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/c607028fa930eb5510c4ba11b1f44845b3b2653c67c4f5e7cfbee6566e89a13a?placeholderIfAbsent=true&apiKey=27c8773822ca4ac8b9cf93169b3bed33"
            alt=""
          />
        </button>
      </div>
      <span className={styles.price}>${price.toFixed(2)}</span>
    </article>
  );
};

export default CartItem;
