/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./CheckoutPage.module.css";
import Header from "./Header";
import CartItem from "./CartItem";
import Summary from "./Summary";
import PaymentSection from "./PaymentSection";

const CheckoutPage = () => {
  const cartItems = [
    {
      id: 1,
      name: "Nike Air Max 270",
      size: "9.5",
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/cfe0d87b77b586c05ad341ab044b5f4b7f19c3e8e7999ad950d9164dc1a33acc?placeholderIfAbsent=true&apiKey=27c8773822ca4ac8b9cf93169b3bed33",
      price: 160.0,
    },
    {
      id: 2,
      name: "Nike Air Max 90",
      size: "9.5",
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/6bb7319a141034581c82596c79e8e0dd284f571efc10960f3093f0ec3162700a?placeholderIfAbsent=true&apiKey=27c8773822ca4ac8b9cf93169b3bed33",
      price: 130.0,
    },
    {
      id: 3,
      name: "Nike Air Cross Trainer 3 Low",
      size: "9.5",
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/f84033c2ed4380363000b81e47a804a02511f9c6c5c47f5be2ed1b72d756a3c0?placeholderIfAbsent=true&apiKey=27c8773822ca4ac8b9cf93169b3bed33",
      price: 125.0,
    },
  ];

  return (
    <main className={styles.checkoutPage}>
      <Header />
      <div className={styles.container}>
        
        <div className={styles.content}>
          <section className={styles.cartSection}>
            <h2 className={styles.sectionTitle}>Cart</h2>
            <p className={styles.sectionDescription}>
              Check your cart items before proceeding to payment.
            </p>
            {cartItems.map((item) => (
              <CartItem key={item.id} {...item} />
            ))}
          </section>
          <aside className={styles.summarySection}>
            <Summary />
            <PaymentSection />
          </aside>
        </div>
      </div>
    </main>
  );
};

export default CheckoutPage;
