/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./LoginPage.module.css";

function LoginForm() {
  const socialIcons = [
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/33ec2f74dbcc4e20cbc4efa8318f02b7cb0a37762ce04ee24463bea2ae7e4195?placeholderIfAbsent=true&apiKey=27c8773822ca4ac8b9cf93169b3bed33",
      alt: "Facebook",
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/e1491214b63d0e43ddf623ddce4b682a463034f81738cf5e570e1fa444cdb1a1?placeholderIfAbsent=true&apiKey=27c8773822ca4ac8b9cf93169b3bed33",
      alt: "Twitter",
    },
  ];

  return (
    <section className={styles.loginFormSection}>
      <form className={styles.loginForm}>
        <h1 className={styles.greeting}>Hello,</h1>
        <h2 className={styles.welcome}>welcome</h2>
        <label htmlFor="username" className="visually-hidden">
          Username
        </label>
        <input
          type="text"
          id="username"
          placeholder="USERNAME"
          className={styles.inputField}
        />
        <label htmlFor="password" className="visually-hidden">
          Password
        </label>
        <input
          type="password"
          id="password"
          placeholder="PASSWORD"
          className={styles.inputField}
        />
        <div className={styles.formOptions}>
          <div className={styles.showPasswordWrapper}>
            <input
              type="checkbox"
              id="showPassword"
              className={styles.checkbox}
            />
            <label htmlFor="showPassword" className={styles.showPasswordLabel}>
              Show Password
            </label>
          </div>
          <a href="#" className={styles.forgotPassword}>
            Forgot password
          </a>
        </div>
        <button type="submit" className={styles.loginButton}>
          Login
        </button>
        <p className={styles.followText}>Follow</p>
        <div className={styles.socialIcons}>
          {socialIcons.map((icon, index) => (
            <img
              key={index}
              src={icon.src}
              alt={icon.alt}
              className={styles.socialIcon}
            />
          ))}
        </div>
      </form>
    </section>
  );
}

export default LoginForm;
