/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./LoginPage.module.css";
import Header from "./Header";
import LoginForm from "./LoginForm";
import Footer from "./Footer";

function LoginPage() {
  return (
    <main className={styles.loginPage}>
      <div className={styles.contentWrapper}>
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/99824a119e724d7fedf2656cdf91f86e2b23daf9c85b5f58dd85edad32bac843?placeholderIfAbsent=true&apiKey=27c8773822ca4ac8b9cf93169b3bed33"
          alt=""
          className={styles.backgroundImage}
        />
        <div className={styles.contentContainer}>
          <Header />
          <LoginForm />
        </div>
      </div>
      <Footer />
    </main>
  );
}

export default LoginPage;
