/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./Footer.module.css";

const Footer = () => {
  return (
    <footer className={styles.footer}>
      <div className={styles.footerContent}>
        <div className={styles.aboutSection}>
          <h2>About Us</h2>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec
            odio. Praesent libero. Sed cursus ante dapibus diam.
          </p>
        </div>
        <div className={styles.linksSection}>
          <h2>Quick Links</h2>
          <nav>
            <ul>
              <li>
                <a href="#home">Home</a>
              </li>
              <li>
                <a href="#about">About</a>
              </li>
              <li>
                <a href="#services">Services</a>
              </li>
              <li>
                <a href="#contact">Contact</a>
              </li>
            </ul>
          </nav>
        </div>
        <div className={styles.socialSection}>
          <h2>Follow Us</h2>
          <div className={styles.socialIcons}>
            <a href="#" aria-label="Facebook">
              <img
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/a45fc6a40956ccccb8738bf4972082ee0c8506cabec091f36224e5a1f6fd22c3?placeholderIfAbsent=true&apiKey=27c8773822ca4ac8b9cf93169b3bed33"
                alt=""
              />
            </a>
            <a href="#" aria-label="Twitter">
              <img
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/bfad15def37d2a473e9f31d175d45d923a2bc1eb9d0a70561b89d546f371bc72?placeholderIfAbsent=true&apiKey=27c8773822ca4ac8b9cf93169b3bed33"
                alt=""
              />
            </a>
            <a href="#" aria-label="Instagram">
              <img
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/1058894cdc262021057390a64208e8478cf0fd6734ec96748b671cc2ac52f5b1?placeholderIfAbsent=true&apiKey=27c8773822ca4ac8b9cf93169b3bed33"
                alt=""
              />
            </a>
          </div>
        </div>
        <div className={styles.contactSection}>
          <h2>Contact Us</h2>
          <address>
            Email: info@example.com
            <br />
            Phone: +123 456 7890
            <br />
            Address: 123 Street Name, City, Country
          </address>
        </div>
      </div>
      <div className={styles.copyright}>
        <p>2024 Your Website. All Rights Reserved.</p>
      </div>
    </footer>
  );
};

export default Footer;
