/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./Rugby.module.css";
import Header from "./Header";
import ProductCard from "./ProductCard";
import Banner from "./Banner";
import Footer from "./Footer";

const Rugby = () => {
  const products = [
    {
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/a1adfb13bec2d66c3f842dced8d51295f17a91f274c3b0779b280e4df5d73bf0?placeholderIfAbsent=true&apiKey=27c8773822ca4ac8b9cf93169b3bed33",
      name: "Gilbert Rugby Match Ball",
      price: "$13",
      rating: 1,
    },
    {
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/ca9020c0b3399c4cb6d61b642f9607b9588d9f793d2b779348742f3c0f5e80cc?placeholderIfAbsent=true&apiKey=27c8773822ca4ac8b9cf93169b3bed33",
      name: "Canterbury Rugby shorts",
      price: "$8",
      rating: 2,
    },
    {
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/554a934cbfac7382eee07b0f825ff873c167205865f805ad0f29da22ceaf2c5e?placeholderIfAbsent=true&apiKey=27c8773822ca4ac8b9cf93169b3bed33",
      name: "Gilbert GTR3000 Rugby Ball",
      price: "$24",
      rating: 3,
    },
    {
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/5dff25f80a174ed6e68094f60bf6b2f5e321ac79b10d0f6fb72fb586ed75a39f?placeholderIfAbsent=true&apiKey=27c8773822ca4ac8b9cf93169b3bed33",
      name: "Rugby head gear",
      price: "$20",
      rating: 1,
    },
    {
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/edfc8571192a016c4adb2aa70d97c88d3d8b96d1a60b7c67aa578818ef19b039?placeholderIfAbsent=true&apiKey=27c8773822ca4ac8b9cf93169b3bed33",
      name: "Rugby jersey 2023",
      price: "$18",
      rating: 2,
    },
    {
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/7e75064c35ab580fad923e13cb535c0a9f37350a447fa0ec1bb77af2a99d210f?placeholderIfAbsent=true&apiKey=27c8773822ca4ac8b9cf93169b3bed33",
      name: "Elastoplaster , Elasto Plaster, Adhesive Plaster",
      price: "$6",
      rating: 1,
    },
    {
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/7b393a5163fc99c2c7e92063b0d2877a01c01766d3fc6d8bf44570c9800186f5?placeholderIfAbsent=true&apiKey=27c8773822ca4ac8b9cf93169b3bed33",
      name: "adidas Kakari SG Rugby Boots",
      price: "$85",
      rating: 4,
    },
    {
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/42ac90cb21f1544f1098a4ba357c8a2fdbfc60705e69f256863f6c8caec6ccbf?placeholderIfAbsent=true&apiKey=27c8773822ca4ac8b9cf93169b3bed33",
      name: "Canterbury Rugby shorts with padded",
      price: "$7",
      rating: 2,
    },
  ];

  return (
    <main className={styles.rugbyMain}>
      <Header />
      <section className={styles.productSection}>
        <h1 className={styles.sectionTitle}>Rugby</h1>
        <div className={styles.productGrid}>
          {products.map((product, index) => (
            <ProductCard key={index} {...product} />
          ))}
        </div>
      </section>
      <Banner />
      <Footer />
    </main>
  );
};

export default Rugby;
