/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./Footer.module.css";

function Footer() {
  return (
    <footer className={styles.footer}>
      <div className={styles.footerContent}>
        <div className={styles.footerSection}>
          <h3 className={styles.sectionTitle}>About Us</h3>
          <p className={styles.sectionText}>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec
            odio. Praesent libero. Sed cursus ante dapibus diam.
          </p>
        </div>
        <div className={styles.footerSection}>
          <h3 className={styles.sectionTitle}>Quick Links</h3>
          <nav className={styles.quickLinks}>
            <a href="#home" className={styles.footerLink}>
              Home
            </a>
            <a href="#about" className={styles.footerLink}>
              About
            </a>
            <a href="#services" className={styles.footerLink}>
              Services
            </a>
            <a href="#contact" className={styles.footerLink}>
              Contact
            </a>
          </nav>
        </div>
        <div className={styles.footerSection}>
          <h3 className={styles.sectionTitle}>Social Media</h3>
          <div className={styles.socialIcons}>
            <a href="#" className={styles.socialIcon} aria-label="Facebook"></a>
            <a href="#" className={styles.socialIcon} aria-label="Twitter"></a>
            <a
              href="#"
              className={styles.socialIcon}
              aria-label="Instagram"
            ></a>
          </div>
        </div>
        <div className={styles.footerSection}>
          <h3 className={styles.sectionTitle}>Contact Us</h3>
          <address className={styles.contactInfo}>
            Email: info@example.com
            <br />
            Phone: +123 456 7890
            <br />
            Address: 123 Street Name, City, Country
          </address>
        </div>
      </div>
      <div className={styles.copyrightBar}>
        <p className={styles.copyrightText}>
          2024 Your Website. All Rights Reserved.
        </p>
      </div>
    </footer>
  );
}

export default Footer;
