/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./SignUpPage.module.css";
import Header from "./Header";
import SignUpForm from "./SignUpForm";
import Footer from "../Home/components/Footer";

function SignUpPage() {
  return (
    <main className={styles.signUpPage}>
      <div className={styles.contentWrapper}>
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/be0ac5e3b1ff79aa45cf0164d8327214a120ba812ce05925ee13c7a5fd93961f?placeholderIfAbsent=true&apiKey=27c8773822ca4ac8b9cf93169b3bed33"
          alt=""
          className={styles.backgroundImage}
        />
        
        <div className={styles.contentContainer}>
          <Header />
          <SignUpForm />
        </div>
      </div>
      <Footer />
    </main>
  );
}

export default SignUpPage;
