/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./SignUpForm.module.css";

function SignUpForm() {
  return (
    <section className={styles.signUpSection}>
      <h1 className={styles.greeting}>Hello,</h1>
      <h2 className={styles.welcome}>welcome</h2>
      <form className={styles.signUpForm}>
        <label htmlFor="name" className="visually-hidden">
          Name
        </label>
        <input
          type="text"
          id="name"
          placeholder="NAME"
          className={styles.inputField}
        />

        <label htmlFor="username" className="visually-hidden">
          Username
        </label>
        <input
          type="text"
          id="username"
          placeholder="USERNAME"
          className={styles.inputField}
        />

        <label htmlFor="email" className="visually-hidden">
          Email
        </label>
        <input
          type="email"
          id="email"
          placeholder="EMAIL"
          className={styles.inputField}
        />

        <label htmlFor="password" className="visually-hidden">
          Password
        </label>
        <input
          type="password"
          id="password"
          placeholder="PASSWORD"
          className={styles.inputField}
        />

        <button type="submit" className={styles.signUpButton}>
          Sign up
        </button>
      </form>
      <p className={styles.followText}>Follow</p>
      <div className={styles.socialIcons}>
        <a
          href="#"
          className={styles.socialIcon}
          aria-label="Follow us on Facebook"
        ></a>
        <a
          href="#"
          className={styles.socialIcon}
          aria-label="Follow us on Twitter"
        ></a>
      </div>
    </section>
  );
}

export default SignUpForm;
