/**
 * This code was generated by Builder.io.
 */
import React from "react";
import MainComponent from "./MainComponent";
import Footer from "./Footer";
import WhoWeAre from "./WhoWeAre";
import OurMission from "./OurMission";
import CustomerCare from "./CustomerCare";
import WhyChooseUs from "./WhyChooseUs";
import styles from "./AboutUs.module.css";


const AboutUs = () =>  {
  return (
    <div className={styles.aboutUsPage}>
      <MainComponent />
      
      <main className={styles.mainContent}>
      <div className={styles.heroSection}>
       <div className={styles.rectangle}>
          <h1 className={styles.pageTitle}>ABOUT US</h1>
          </div>
        <div className={styles.heroSection}>
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/5c8be98f7420b412924ebb2b978f15fc2011b2fa5a0c37a7c6b5d1a562ac1225?placeholderIfAbsent=true&apiKey=2ced3db22aac4ec9b3a268650a41a373"
            alt="About Us hero image"
            className={styles.heroImage}
          />
      </div>
      </div> 
        <WhoWeAre />
        <OurMission />
        <CustomerCare />
        <WhyChooseUs />
      </main>
      <Footer />
      
    </div>
  );
};

export default AboutUs;
