/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./Footer.module.css";

const Footer = () =>  { 
  return (
    <footer className={styles.footer}>
      <div className={styles.footerContent}>
        <div className={styles.aboutSection}>
          <h3>About Us</h3>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec
            odio. Praesent libero. Sed cursus ante dapibusdiamwith the.
          </p>
        </div>
        <nav className={styles.quickLinks}>
          <h3>Quick Links</h3>
          <ul>
            <li>
              <a href="/">Home</a>
            </li>
            <li>
              <a href="/about">About</a>
            </li>
            <li>
              <a href="/services">Services</a>
            </li>
            <li>
              <a href="/contact">Contact</a>
            </li>
          </ul>
        </nav>
        <div className={styles.socialLinks}>
          <h3>Follow Us</h3>
          <div className={styles.socialIcons}>
            <a href="#" aria-label="Facebook">
              <img
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/108272a36be56296477b5f03aac97ece0f1c3ae0f4eaecb62b6813c231636fc2?placeholderIfAbsent=true&apiKey=2ced3db22aac4ec9b3a268650a41a373"
                alt=""
              />
            </a>
            <a href="#" aria-label="Twitter">
              <img
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/95ae4a3130faa27b5bfd1f8111498617af1dfe02ebdad29114ca4245db477c7c?placeholderIfAbsent=true&apiKey=2ced3db22aac4ec9b3a268650a41a373"
                alt=""
              />
            </a>
            <a href="#" aria-label="Instagram">
              <img
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/23d75f700d21d7269da4c80ff38f437acc38e3063e15c3959f2eecc4560dbaed?placeholderIfAbsent=true&apiKey=2ced3db22aac4ec9b3a268650a41a373"
                alt=""
              />
            </a>
          </div>
        </div>
        <div className={styles.contactInfo}>
          <h3>Contact Us</h3>
          <p>Email: info@example.com</p>
          <p>Phone: +123 456 7890</p>
          <p>Address: 123 Street Name, City, Country</p>
        </div>
      </div>
      <div className={styles.divider}></div>
      <div className={styles.copyright}>
        <p>&copy; 2024 Your Website. All Rights Reserved.</p>
      </div>
    </footer>
  );
};

export default Footer;
