/**
 * This code was generated by Builder.io.
 */
import React from "react";
import NavigationBar from "./NavigationBar";
import styles from "./MainComponent.module.css";

const MainComponent = () => {
  return (
    <main >
      
      <div >
        <NavigationBar />
        <div>
        
        </div>
      </div>
    </main>
  );
};

export default MainComponent;
