/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./NavigationBar.module.css";

function NavItem({ text, isHome }) {
  return (
    <a href="#" className={`${styles.navItem} ${isHome ? styles.home : ""}`}>
      {text}
    </a>
  );
}

export default NavItem;
