/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./OurMission.module.css";

function OurMission() {
  return (
    <section className={styles.ourMission}>
      <h2 className={styles.sectionTitle}>OUR MISSION</h2>
      <p className={styles.missionStatement}>
        At [Your Company Name], we are passionate about sports, committed to
        excellence, and dedicated to capturing the moments that matter. Whether
        you're an athlete, a fan, or an organization, our goal is to enhance
        your experience through our specialized services in sports photography
        and exceptional customer care.
      </p>
    </section>
  );
}

export default OurMission;
