/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./WhoWeAre.module.css";

function WhoWeAre() {
  return (
    <section className={styles.whoWeAre}>
      <h2 className={styles.sectionTitle}>WHO WE ARE</h2>
      <div className={styles.content}>
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/37629e3201791a53fb5375df926a879fa84eec290b54f06a9c325a199af37913?placeholderIfAbsent=true&apiKey=2ced3db22aac4ec9b3a268650a41a373"
          alt="Team photo"
          className={styles.teamPhoto}
        />
        <p className={styles.description}>
          At [Your Company Name], we are passionate about sports, committed to
          excellence, and dedicated to capturing the moments that matter.
          Whether you're an athlete, a fan, or an organization, our goal is to
          enhance your experience through our specialized services in sports
          photography and exceptional customer care.
        </p>
      </div>
    </section>
  );
}

export default WhoWeAre;
