/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./WhyChooseUs.module.css";

function WhyChooseUs() {
  return (
    <section className={styles.whyChooseUs}>
      <h2 className={styles.sectionTitle}>WHY CHOOSE US</h2>
      <div className={styles.content}>
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/42461af6f7ecdaf8921b0a8f95a5d95ff296eeccf451f4b1caab470ed443b78d?placeholderIfAbsent=true&apiKey=2ced3db22aac4ec9b3a268650a41a373"
          alt="Our team in action"
          className={styles.teamImage}
        />
        <ul className={styles.reasonsList}>
          <li>
            <strong>Experience:</strong> With years of experience in the sports
            industry, we know what it takes to deliver outstanding results.
          </li>
          <li>
            <strong>Quality:</strong> We are committed to excellence in
            everything we do, from our photographs to our customer care.
          </li>
          <li>
            <strong>Community:</strong> We are more than just a service
            provider; we are a part of the sports community, dedicated to
            supporting athletes, teams, and fans.
          </li>
        </ul>
      </div>
    </section>
  );
}

export default WhyChooseUs;
